# Generated by Django 5.2.5 on 2025-08-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffes', '0002_alter_user_email'),
    ]

    operations = [
    ]
